### ISSUE TITLE
Allow Tasks to Have Descriptions

### ISSUE THREAD

**Issue by prplmnky** [Armadill0/harbour-tasklist#34]
Many times I want to give tasks arbitrary information like an address or person of contact that would be too verbose to show in the task list. It would be great if this data could be assigned and viewable on a task detail page.

**Comment by Armadill0** [comment]
Thanks for your report. I already had something in mind to realize this.

Implementation todos:
- This additional information could be shown in the list of tasks itself. Due to the fact, that the description of the textSwitch element is already in use for meta information of the task (currently only on smart lists, but it's also planned for normal lists), there should be added another Label or something similar to show the additional editable information.

- For an easier aintenance the current collection of elemnts, which are generated for each Task should be refactored into a meta element.

**Comment by Armadill0** [comment]
Creating a new Task element has already been done with #18.

Database update is needed to add the description capabilities.

**Comment by Armadill0** [comment]
fixed by pull request #46
